# In this directory, run the following command to build this builder.
# $ gcloud builds submit . --config=cloudbuild.yaml

substitutions:
  # Latest Terraform releases:
  # https://releases.hashicorp.com/terraform/
  # use the SHA256SUB for terraform_X.X.X_linux_amd64.zip
  _TERRAFORM_VERSION: 1.4.4
  _TERRAFORM_VERSION_SHA256SUM: 67541c1f6631befcc25b764028e5605e59234d4424e60a256518ee1e8dd50593
  # Latest Terragrunt releases:
  # https://github.com/gruntwork-io/terragrunt/releases/
  # use the SHA256SUB for terragrunt_linux_amd64
  _TERRAGRUNT_VERSION: 0.45.2
  _TERRAGRUNT_VERSION_SHA256SUM: f6e43f576ae5f8c6f24c15105334185cddf39342bbeea334408ef0415e1045da

steps:
  - name: "gcr.io/cloud-builders/docker"
    env:
      - "TERRAFORM_VERSION=${_TERRAFORM_VERSION}"
      - "TERRAFORM_VERSION_SHA256SUM=${_TERRAFORM_VERSION_SHA256SUM}"
      - "TERRAGRUNT_VERSION=${_TERRAGRUNT_VERSION}"
      - "TERRAGRUNT_VERSION_SHA256SUM=${_TERRAGRUNT_VERSION_SHA256SUM}"
    args:
      - "build"
      - --build-arg
      - TERRAFORM_VERSION=${_TERRAFORM_VERSION}
      - --build-arg
      - TERRAFORM_VERSION_SHA256SUM=${_TERRAFORM_VERSION_SHA256SUM}
      - --build-arg
      - TERRAGRUNT_VERSION=${_TERRAGRUNT_VERSION}
      - --build-arg
      - TERRAGRUNT_VERSION_SHA256SUM=${_TERRAGRUNT_VERSION_SHA256SUM}
      - --tag
      - "gcr.io/${PROJECT_ID}/terragrunt:${_TERRAFORM_VERSION}-${_TERRAGRUNT_VERSION}"
      - --tag
      - "gcr.io/${PROJECT_ID}/terragrunt:latest"
      - "."
images:
  - "gcr.io/${PROJECT_ID}/terragrunt:${_TERRAFORM_VERSION}-${_TERRAGRUNT_VERSION}"
  - "gcr.io/${PROJECT_ID}/terragrunt:latest"
tags: ["cloud-builders-community"]
