# In this directory, run the following command to build this builder.
# $ gcloud builds submit . --config=cloudbuild.yaml

substitutions:
  _PROJECT_ID: global-artifact-registry-34e8
  _LOCATION: northamerica-northeast1
  _REPO_NAME: container-repo
  _REPO_URL: "${_LOCATION}-docker.pkg.dev/${_PROJECT_ID}/${_REPO_NAME}"
  # Latest Terraform releases:
  # https://releases.hashicorp.com/terraform/
  # use the SHA256SUB for terraform_X.X.X_linux_amd64.zip
  _TERRAFORM_VERSION: 1.4.6
  _TERRAFORM_VERSION_SHA256SUM: e079db1a8945e39b1f8ba4e513946b3ab9f32bd5a2bdf19b9b186d22c5a3d53b
  # Latest Terragrunt releases:
  # https://github.com/gruntwork-io/terragrunt/releases/
  # use the SHA256SUB for terragrunt_linux_amd64
  _TERRAGRUNT_VERSION: 0.47.0
  _TERRAGRUNT_VERSION_SHA256SUM: 98d45f6bfbfae84b51364c1ad6920f09ecb4d834908b0535e4e331a9fc6fc75b
options:
  # Allow substitutions to reference other substitution values.
  dynamic_substitutions: true

steps:
  - name: "gcr.io/cloud-builders/docker"
    env:
      - "TERRAFORM_VERSION=${_TERRAFORM_VERSION}"
      - "TERRAFORM_VERSION_SHA256SUM=${_TERRAFORM_VERSION_SHA256SUM}"
      - "TERRAGRUNT_VERSION=${_TERRAGRUNT_VERSION}"
      - "TERRAGRUNT_VERSION_SHA256SUM=${_TERRAGRUNT_VERSION_SHA256SUM}"
    args:
      - "build"
      - --build-arg
      - TERRAFORM_VERSION=${_TERRAFORM_VERSION}
      - --build-arg
      - TERRAFORM_VERSION_SHA256SUM=${_TERRAFORM_VERSION_SHA256SUM}
      - --build-arg
      - TERRAGRUNT_VERSION=${_TERRAGRUNT_VERSION}
      - --build-arg
      - TERRAGRUNT_VERSION_SHA256SUM=${_TERRAGRUNT_VERSION_SHA256SUM}
      - --tag
      - "${_REPO_URL}/terragrunt:${_TERRAFORM_VERSION}-${_TERRAGRUNT_VERSION}"
      - --tag
      - "${_REPO_URL}/terragrunt:latest"
      - "."
images:
  - "${_REPO_URL}/terragrunt:${_TERRAFORM_VERSION}-${_TERRAGRUNT_VERSION}"
  - "${_REPO_URL}/terragrunt:latest"
tags: ["cloud-builders-community"]
